# Generated by Django 5.0.7 on 2024-07-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
